### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by RadioActiveLamb** [MicrosoftDocs/OfficeDocs-o365seccomp#185]
The link for "Connect to the Office 365 Security & Compliance Center using remote PowerShell." takes me to the document for connecting to Exchange Online, not the security and compliance center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb598b7-9868-2686-9c57-c50e6e000cd7
* Version Independent ID: 1a3362b5-f106-8e97-df93-30d69daf9a3c
* Content: [Give users access to the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/grant-access-to-the-security-and-compliance-center)
* Content Source: [SecurityCompliance/grant-access-to-the-security-and-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/grant-access-to-the-security-and-compliance-center.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by stephow-MSFT** [comment]
Thanks I've fixed this link.

**Comment by Drtrider** [comment]
This link is still broken: "Connect to Security & Compliance Center PowerShell."

**Comment by RadioActiveLamb** [comment]
Drtrider, this case is closed. You should probably report the issue on the content instead of this case. I'm not sure if the author will see it here.

**Comment by Drtrider** [comment]
> Drtrider, this case is closed. You should probably report the issue on the content instead of this case. I'm not sure if the author will see it here.

Yeah. Already did so. Link: https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/596
