### ISSUE TITLE
Manage your security - ATP post-setup Link

### ISSUE THREAD

**Issue by m80dunn** [MicrosoftDocs/OfficeDocs-o365seccomp#781]
Is this link supposed to send you to https://docs.microsoft.com/en-us/?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5375df5a-9955-47d9-5ef4-8adbd219f77b
* Version Independent ID: 5b191c2a-bfde-a531-9c3b-4b295efea56c
* Content: [Set up Office 365 ATP Safe Links policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-atp-safe-links-policies)
* Content Source: [SecurityCompliance/set-up-atp-safe-links-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-atp-safe-links-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @m80dunn and thank you for the feedback. I reviewed all the links in this article and slightly revised the content. I think the issue is now resolved. Please let us know if you have any other questions.

**Comment by m80dunn** [comment]
The link I was referring to is still the same. Is it supposed to send you to that site? Doesn’t seem right to me. 

Mike Dunn
(Sent from my iPhone)
